version: "3"

services:
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto:latest
    restart: always 
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - 1883:1883

  smartfox-client:
    container_name: smartfox-client
    build: ./
    restart: always 
    depends_on:
      - mqtt-broker
