version: "3"

services:
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse/mosquitto:1.4.8
    ports:
      - 1883:1883

  smartfox-client:
    container_name: smartfox-client
    build: ./
    depends_on:
      - mqtt-broker
